import {AppNav} from "./navigation/AppNav.js"
import {AppSlot} from "./navigation/AppSlot.js"
import {DownloaderForm} from "./download/DownloadForm.js"
import {HttpClient} from "./remote/HttpClient.js"
import {DataClient} from "./remote/DataClient.js"
import {JobList} from "./joblist/JobList.js"