kind: BuildConfig
apiVersion: v1
metadata:
  name: deploy-downloader
  labels:
    app: deploy-downloader
spec:
  resources:
    requests:
      cpu: 2000Mi
      memory: 1G
  runPolicy: Parallel
  source:
    git:
      ref: master
      uri: "https://github.com/alacambra/youtubedl-java-api.git"
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/deploy.oc.Jenkinsfile